// Scenario document set — single source of truth for the six pseudo-
// documents the Cross-Document Consistency agent reads. Per PRD § Modules
// (scenario loader) and Task 7.
//
// IMPORTANT: the demo's expected-document set is SEVEN items (six present
// JSON files + one deliberately missing emergency mitigation receipt).
// The agent must classify the inventory and surface the missing receipt
// as one of its findings.
import fnolTranscript from './fnol-transcript.json';
import contractorEstimate from './contractor-estimate.json';
import fieldInspection from './field-inspection.json';
import noaaWeather from './noaa-weather.json';
import recordedStatement from './recorded-statement.json';
import mortgageStatement from './mortgage-statement.json';

export const DOCUMENT_KINDS = [
  'fnol_transcript',
  'contractor_estimate',
  'field_inspection_report',
  'weather_verification',
  'recorded_statement',
  'mortgage_statement',
  'emergency_mitigation_receipt',
] as const;

export type DocumentKind = (typeof DOCUMENT_KINDS)[number];

export const DOCUMENT_KIND_LABELS: Record<DocumentKind, string> = {
  fnol_transcript: 'FNOL transcript',
  contractor_estimate: 'Contractor estimate',
  field_inspection_report: 'Field inspection report',
  weather_verification: 'Weather verification (NOAA)',
  recorded_statement: 'Recorded statement',
  mortgage_statement: 'Mortgage statement',
  emergency_mitigation_receipt: 'Emergency mitigation receipt',
};

export interface ScenarioDocument {
  id: string;
  kind: DocumentKind;
  title: string;
  filename: string;
  // Public URL of the rendered PDF facsimile. Generated by
  // `npm run generate-pdfs` and committed under public/documents/.
  pdfUrl: string;
  payload: unknown;
}

function pdfUrlFor(id: string): string {
  return `/documents/${id}.pdf`;
}

// Each entry is the parsed JSON file as the agent will see it. We pass
// the full JSON string into the prompt — no schema gymnastics — because
// the model's job is to classify and cross-reference these as if they
// were uploaded artifacts.
export const SCENARIO_DOCUMENTS: ScenarioDocument[] = [
  {
    id: fnolTranscript.id,
    kind: fnolTranscript.kind as DocumentKind,
    title: fnolTranscript.title,
    filename: fnolTranscript.filename,
    pdfUrl: pdfUrlFor(fnolTranscript.id),
    payload: fnolTranscript,
  },
  {
    id: contractorEstimate.id,
    kind: contractorEstimate.kind as DocumentKind,
    title: contractorEstimate.title,
    filename: contractorEstimate.filename,
    pdfUrl: pdfUrlFor(contractorEstimate.id),
    payload: contractorEstimate,
  },
  {
    id: fieldInspection.id,
    kind: fieldInspection.kind as DocumentKind,
    title: fieldInspection.title,
    filename: fieldInspection.filename,
    pdfUrl: pdfUrlFor(fieldInspection.id),
    payload: fieldInspection,
  },
  {
    id: noaaWeather.id,
    kind: noaaWeather.kind as DocumentKind,
    title: noaaWeather.title,
    filename: noaaWeather.filename,
    pdfUrl: pdfUrlFor(noaaWeather.id),
    payload: noaaWeather,
  },
  {
    id: recordedStatement.id,
    kind: recordedStatement.kind as DocumentKind,
    title: recordedStatement.title,
    filename: recordedStatement.filename,
    pdfUrl: pdfUrlFor(recordedStatement.id),
    payload: recordedStatement,
  },
  {
    id: mortgageStatement.id,
    kind: mortgageStatement.kind as DocumentKind,
    title: mortgageStatement.title,
    filename: mortgageStatement.filename,
    pdfUrl: pdfUrlFor(mortgageStatement.id),
    payload: mortgageStatement,
  },
];

export function getDocumentById(id: string): ScenarioDocument | undefined {
  return SCENARIO_DOCUMENTS.find((d) => d.id === id);
}

// What the carrier expects to see in a complete homeowners hailstorm
// claim file. Anything in this list that isn't in SCENARIO_DOCUMENTS is
// "missing" — used for ground-truth verification of the agent's missing-
// document finding.
export const REQUIRED_DOCUMENT_KINDS: readonly DocumentKind[] = [
  'fnol_transcript',
  'contractor_estimate',
  'field_inspection_report',
  'weather_verification',
  'recorded_statement',
  'mortgage_statement',
  'emergency_mitigation_receipt',
];

export function getMissingRequiredKinds(): DocumentKind[] {
  const present = new Set(SCENARIO_DOCUMENTS.map((d) => d.kind));
  return REQUIRED_DOCUMENT_KINDS.filter((k) => !present.has(k));
}
